// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proto/rpc_proto/hello.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"` // 这个是在创建一个通行证账号时赋予这个账号在这个项目的识别码，相同账号的该码不会被改变。游戏登录操作需要该码找到玩家的role。
}

func (x *CS_Login) Reset() {
	*x = CS_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proto_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Login) ProtoMessage() {}

func (x *CS_Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Login.ProtoReflect.Descriptor instead.
func (*CS_Login) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_hello_proto_rawDescGZIP(), []int{0}
}

func (x *CS_Login) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type SC_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode   int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	SessionId uint64 `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	OpenId    string `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`
	UserId    uint64 `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *SC_Login) Reset() {
	*x = SC_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proto_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Login) ProtoMessage() {}

func (x *SC_Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Login.ProtoReflect.Descriptor instead.
func (*SC_Login) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SC_Login) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *SC_Login) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SC_Login) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SC_Login) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CS_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CS_Message) Reset() {
	*x = CS_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proto_hello_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Message) ProtoMessage() {}

func (x *CS_Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_hello_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Message.ProtoReflect.Descriptor instead.
func (*CS_Message) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_hello_proto_rawDescGZIP(), []int{2}
}

func (x *CS_Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SC_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SC_Message) Reset() {
	*x = SC_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proto_hello_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Message) ProtoMessage() {}

func (x *SC_Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_hello_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Message.ProtoReflect.Descriptor instead.
func (*SC_Message) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_hello_proto_rawDescGZIP(), []int{3}
}

func (x *SC_Message) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *SC_Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SC_DisconnectNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason int32 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *SC_DisconnectNotify) Reset() {
	*x = SC_DisconnectNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proto_hello_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_DisconnectNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_DisconnectNotify) ProtoMessage() {}

func (x *SC_DisconnectNotify) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_hello_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_DisconnectNotify.ProtoReflect.Descriptor instead.
func (*SC_DisconnectNotify) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_hello_proto_rawDescGZIP(), []int{4}
}

func (x *SC_DisconnectNotify) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

var File_proto_rpc_proto_hello_proto protoreflect.FileDescriptor

var file_proto_rpc_proto_hello_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x08, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x08, 0x53, 0x43, 0x5f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x0a,
	0x43, 0x53, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x43, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x43, 0x5f, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x6e, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x12, 0x2e, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x0d, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x67, 0x61, 0x69,
	0x6e, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x53, 0x5f, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x43, 0x5f, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_proto_hello_proto_rawDescOnce sync.Once
	file_proto_rpc_proto_hello_proto_rawDescData = file_proto_rpc_proto_hello_proto_rawDesc
)

func file_proto_rpc_proto_hello_proto_rawDescGZIP() []byte {
	file_proto_rpc_proto_hello_proto_rawDescOnce.Do(func() {
		file_proto_rpc_proto_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_proto_hello_proto_rawDescData)
	})
	return file_proto_rpc_proto_hello_proto_rawDescData
}

var file_proto_rpc_proto_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rpc_proto_hello_proto_goTypes = []interface{}{
	(*CS_Login)(nil),            // 0: proto.CS_Login
	(*SC_Login)(nil),            // 1: proto.SC_Login
	(*CS_Message)(nil),          // 2: proto.CS_Message
	(*SC_Message)(nil),          // 3: proto.SC_Message
	(*SC_DisconnectNotify)(nil), // 4: proto.SC_DisconnectNotify
}
var file_proto_rpc_proto_hello_proto_depIdxs = []int32{
	0, // 0: proto.Greeter.SayHello:input_type -> proto.CS_Login
	0, // 1: proto.Greeter.SayHelloAgain:input_type -> proto.CS_Login
	1, // 2: proto.Greeter.SayHello:output_type -> proto.SC_Login
	1, // 3: proto.Greeter.SayHelloAgain:output_type -> proto.SC_Login
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_proto_hello_proto_init() }
func file_proto_rpc_proto_hello_proto_init() {
	if File_proto_rpc_proto_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_proto_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proto_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proto_hello_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proto_hello_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proto_hello_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_DisconnectNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_proto_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_proto_hello_proto_goTypes,
		DependencyIndexes: file_proto_rpc_proto_hello_proto_depIdxs,
		MessageInfos:      file_proto_rpc_proto_hello_proto_msgTypes,
	}.Build()
	File_proto_rpc_proto_hello_proto = out.File
	file_proto_rpc_proto_hello_proto_rawDesc = nil
	file_proto_rpc_proto_hello_proto_goTypes = nil
	file_proto_rpc_proto_hello_proto_depIdxs = nil
}
